// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCoreAPIDemo;

namespace MyCoreAPIDemo.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190601044940_MyCoreAPIDemo.Entities.LibraryContextSeed")]
    partial class MyCoreAPIDemoEntitiesLibraryContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyCoreAPIDemo.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AuthorId");

                    b.ToTable("Author","dbo");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("312f68a4-a401-45b1-883e-51932bee5b19"),
                            FirstName = "Bob",
                            Genre = "Drama",
                            LastName = "Ross"
                        },
                        new
                        {
                            AuthorId = new Guid("08b36a1d-f2ec-4ba4-b1f2-65391e5ec709"),
                            FirstName = "David",
                            Genre = "Fantasy",
                            LastName = "Miller"
                        });
                });

            modelBuilder.Entity("MyCoreAPIDemo.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Descrption")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MyCoreAPIDemo.Entities.Book", b =>
                {
                    b.HasOne("MyCoreAPIDemo.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
